name: Build and Test 🚀

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '8.0.x'
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 📦
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Dependencies 🔄
        run: dotnet restore WebApi

      - name: Build Solution 🔨
        run: dotnet build WebApi -c Release --no-restore

      - name: Run Tests ✅
        run: dotnet test WebApi --no-build --verbosity normal

      - name: Build Docker Image 🐳
        if: success() # This ensures the Docker build only happens if tests pass
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Log in to GitHub Container Registry 🔑
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker Image 🚢
        if: success() # This ensures the Docker push only happens if tests pass
        run: docker push ghcr.io/${{ github.repository }}/webapi:latest
