name: Build, Test, Dockerize! 🚀

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ github.repository }}
  DOTNET_VERSION: '8.0.x'
  SOLUTION_NAME: 'AshamedApp'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup .NET SDK
      - name: Setup .NET 📦
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Restore project dependencies
      - name: Restore Dependencies 🔄
        run: dotnet restore ${{ env.SOLUTION_NAME }}.sln

      # Build the solution
      - name: Build Solution 🔨
        run: dotnet build ${{ env.SOLUTION_NAME }}.sln -c Release --no-restore

      # Run tests
      - name: Run Tests ✅
        run: dotnet test ${{ env.SOLUTION_NAME }}.Tests/${{ env.SOLUTION_NAME }}.Tests.csproj -c Release --no-build --verbosity normal

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Publish the application to the 'publish' directory
      - name: Publish Application 🔨
        run: dotnet publish "AshamedApp.API/AshamedApp.API.csproj" -c Release -o ./publish /p:UseAppHost=false

      # Build Docker image
      - name: Build Docker Image 🐳
        run: docker build -t ${{ env.IMAGE_NAME }} .

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry 🔑
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      # Push Docker image to the registry
      - name: Push Docker Image 🚢
        run: |
          docker tag ${{ env.IMAGE_NAME }}:latest ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest
