name: Build, Test, Dockerize! 🚀

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ github.repository }}
  DOTNET_VERSION: '8.0.x'
  SOLUTION_NAME: 'AshamedApp'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 📦
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Dependencies 🔄
        run: dotnet restore ${{ env.SOLUTION_NAME }}.sln

      - name: Build Solution 🔨
        run: dotnet build ${{ env.SOLUTION_NAME }}.sln -c Release --no-restore

      - name: Run Tests ✅
        run: dotnet test ${{ env.SOLUTION_NAME }}.Tests/${{ env.SOLUTION_NAME }}.Tests.csproj --no-build --verbosity normal

      - name: Build Docker Image 🐳
        if: success()
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Log in to GitHub Container Registry 🔑
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker Image 🚢
        if: success()
        run: docker push ghcr.io/${{ github.repository }}:latest
